name: CI

on:
  pull_request:
    branches:
    - master

jobs:
  lint:
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
    - name: Setup Node
      uses: actions/setup-node@v2.1.2
      with:
        node-version: '12.x'
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: yarn install
    - name: Check formatting
      run: yarn format:check
    - name: Lint
      run: yarn lint --quiet
    - name: Test
      run: yarn jest
