name: Deploy Docker image

on:
  workflow_run:
    workflows:
      - ci
    branches:
      - main
    types:
      - completed

jobs:
  buildx:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Build images
        env:
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          printenv DOCKERHUB_PASSWORD | docker login --username markokajzer --password-stdin
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --tag markokajzer/discord-soundbot:latest \
            --push \
            .
